const presidents = [
  {
    name: "George Washington",
    alive: "false",
    presidentnumber: "1",
    presidency: [1789, 1797],
    militarybackground: "true",
    age: "67",
  },
  {
    name: "Abraham Lincoln",
    alive: "false",
    presidentnumber: "16",
    presidency: [1861, 1865],
    militarybackground: "false",
    age: "56",
  },
  {
    name: "Joe Biden",
    alive: "true",
    presidentnumber: "46",
    presidency: [2021, 2025],
    militarybackground: "false",
    age: "80",
  },
  {
    name: "Jimmy Carter",
    alive: "true",
    presidentnumber: "39",
    presidency: [1977, 1981],
    militarybackground: "true",
    age: "98",
  },
  {
    name: "Theodore Roosevelt",
    alive: "false",
    presidentnumber: "26",
    presidency: [1901, 1909],
    militarybackground: "true",
    age: "60",
  },
  {
    name: "Barack Obama    ",
    alive: "true",
    presidentnumber: "44",
    presidency: [2008, 2016],
    militarybackground: "false",
    age: "61",
  },
];
console.log(presidents);
